"""Reaction sanity checker — format-agnostic (works with JSON and YAML builders).

Importable module — no CLI.

Usage
-----
    from reaction_sanity_check import run_all_checks
    results = run_all_checks(rxns)          # pass your pre-loaded list

Individual checks are also importable:
    check_balances, check_species_continuity,
    check_chain_sets, check_name_similarity, check_zero_rates,
    check_irreversible_flow, check_parameter_conflicts

Each check returns a structured dataclass; companion print_* functions format
the results for notebook display.

Works with ElementaryReaction objects from reaction_model_builder.

Both produce identical ElementaryReaction objects with the same interface.
"""
from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from difflib import SequenceMatcher
from typing import Any, Protocol, runtime_checkable

# ─────────────────────────────────────────────────────────────────────────────
_CARBON_PREFIX = re.compile(r"^C(\d+)$")
_CHAIN_PREFIX  = re.compile(r"^C(\d+)_(.+)$")

DEFAULT_MOIETIES: list[str] = ["CoA", "ACP", "NAD", "NADP"]
DEFAULT_SIMILARITY_THRESHOLD: float = 0.90
DEFAULT_TOLERANCE: float = 1e-9


@runtime_checkable
class _Reaction(Protocol):
    """Structural protocol matching ElementaryReaction from either builder."""
    rxn_name: str
    reactants: dict[str, float]
    products: dict[str, float]
    rate_const_value: float
    reversible: bool
    rvs_rate_const_value: float | None
    rate_const_key: str | None
    rvs_rate_const_key: str | None

    def reaction_expression(self) -> str: ...


# ═══════════════════════════════════════════════════════════════════════════
# Data classes
# ═══════════════════════════════════════════════════════════════════════════

@dataclass
class BalanceResult:
    """Results of the balance check across all reactions."""
    imbalanced: list[tuple[str, str, dict[str, float]]]  # (rxn_name, expression, {moiety: delta})
    balanced_count: int
    moieties: list[str]


@dataclass
class ContinuityResult:
    """Results of the species continuity check."""
    never_created_fwd: list[str]              # never appear as a forward product
    never_consumed: list[str]                 # never appear as a reactant
    single_rxn_species: list[tuple[str, str]] # (species_name, rxn_name) — appear in exactly one reaction
    species_to_rxns: dict[str, set[str]]


@dataclass
class ChainFamilyResult:
    """Chain-length production/consumption audit for a single species family."""
    family: str
    is_unsat: bool
    producer_chains: set[int]
    consumer_chains: set[int]

    @property
    def orphaned_products(self) -> set[int]:
        """Produced at these chains but never consumed — possible missing downstream reaction."""
        return self.producer_chains - self.consumer_chains

    @property
    def orphaned_reactants(self) -> set[int]:
        """Consumed at these chains but never produced — possible typo or missing upstream reaction."""
        return self.consumer_chains - self.producer_chains

    @property
    def is_pure_sink(self) -> bool:
        """Family never consumed: expected terminal product or genuine output."""
        return len(self.consumer_chains) == 0 and len(self.producer_chains) > 0

    @property
    def is_pure_source(self) -> bool:
        """Family never produced: expected external substrate or possible typo."""
        return len(self.producer_chains) == 0 and len(self.consumer_chains) > 0


@dataclass
class SimilarityWarning:
    """A suspiciously similar pair of names (species families or parameter keys)."""
    family_a: str
    family_b: str
    score: float
    note: str
    kind: str = "species"  # "species" or "parameter"


@dataclass
class ZeroRateResult:
    """A reaction that has at least one zero rate constant."""
    rxn_name: str
    expression: str
    direction: str  # "forward", "reverse", or "both"


@dataclass
class IrreversibleFlowResult:
    """Species with a one-way irreversible flow imbalance.

    irrev_gen_never_consumed — generated by at least one irreversible forward
        reaction but never consumed anywhere in the network (will accumulate).
    irrev_consumed_never_gen — consumed by at least one irreversible forward
        reaction but never generated anywhere in the network (will drain).
    Each entry is (species_name, [rxn_name, ...]) listing the responsible
    irreversible reaction(s).
    """
    irrev_gen_never_consumed: list[tuple[str, list[str]]]
    irrev_consumed_never_gen: list[tuple[str, list[str]]]


@dataclass
class ParamConflictResult:
    """A parameter name assigned two or more different values across reactions."""
    param_name: str
    assignments: list[tuple[str, str, float]]  # (rxn_name, direction, value)


# ═══════════════════════════════════════════════════════════════════════════
# Internal helpers
# ═══════════════════════════════════════════════════════════════════════════

def _section(title: str) -> None:
    print("═" * 62)
    print(title)


_TABLE_MAX_HEIGHT = "300px"


def _display_df(records: list[dict]) -> None:
    """Render a list of records as a DataFrame (Jupyter) or plain text table (terminal)."""
    if not records:
        return
    try:
        import pandas as pd
        df = pd.DataFrame(records).fillna("---")
        try:
            from IPython.display import display as _ipy_display, HTML as _HTML
            html = (
                f'<div style="max-height:{_TABLE_MAX_HEIGHT};overflow-y:auto;">'
                + df.to_html(index=False)
                + "</div>"
            )
            _ipy_display(_HTML(html))
        except ImportError:
            print(df.to_string(index=False))
    except ImportError:
        cols = list(records[0].keys())
        rows = [[str(r.get(c) or "") for c in cols] for r in records]
        widths = [max(len(c), *(len(row[i]) for row in rows)) for i, c in enumerate(cols)]
        sep = "  "
        print(sep.join(c.ljust(w) for c, w in zip(cols, widths)))
        print("-" * (sum(widths) + len(sep) * (len(cols) - 1)))
        for row in rows:
            print(sep.join(s.ljust(w) for s, w in zip(row, widths)))


def _count_moiety(species_name: str, moiety: str) -> float:
    """Count the number of a given biochemical moiety in a species name.

    Rules
    -----
    "CoA"  — tokens ending with "CoA"   (catches CoA, MalCoA, AcCoA, ...)
    "ACP"  — tokens ending with "ACP"   (catches ACP, MalACP, BKeAcACP, ...)
    "NAD"  — tokens in {NAD, NADH}      combined NAD+/NADH pool
    "NADP" — tokens in {NADP, NADPH}    combined NADP+/NADPH pool
    other  — exact token equality
    """
    count = 0.0
    for token in species_name.split("_"):
        if moiety == "CoA":
            if token.endswith("CoA"):
                count += 1.0
        elif moiety == "ACP":
            if token.endswith("ACP"):
                count += 1.0
        elif moiety == "NAD":
            if token in ("NAD", "NADH"):
                count += 1.0
        elif moiety == "NADP":
            if token in ("NADP", "NADPH"):
                count += 1.0
        else:
            if token == moiety:
                count += 1.0
    return count


def _carbon_count(species_name: str) -> float:
    """Return the carbon number encoded as the C{N} prefix, or 0 if absent."""
    first_token = species_name.split("_", 1)[0]
    m = _CARBON_PREFIX.match(first_token)
    return float(m.group(1)) if m else 0.0


def _compute_deltas(
    reaction: _Reaction, moieties: list[str]
) -> dict[str, float]:
    """Net change (products − reactants) for carbon and each moiety."""
    deltas: dict[str, float] = defaultdict(float)
    for name, coeff in reaction.reactants.items():
        c = float(coeff)
        deltas["carbon"] -= c * _carbon_count(name)
        for m in moieties:
            deltas[m] -= c * _count_moiety(name, m)
    for name, coeff in reaction.products.items():
        c = float(coeff)
        deltas["carbon"] += c * _carbon_count(name)
        for m in moieties:
            deltas[m] += c * _count_moiety(name, m)
    return dict(deltas)


def _extract_family(species_name: str) -> tuple[str, int | None, bool]:
    """Split a species name into (family, chain_length, is_unsat).

    Examples
    --------
    "C4_BKeAcACP"         → ("BKeAcACP",        4,    False)
    "C12_BHyAcACP_un"     → ("BHyAcACP",        12,   True)
    "C7_FabB_Act_MalACP"  → ("FabB_Act_MalACP", 7,    False)
    "ACP"                 → ("ACP",              None, False)
    "NADPH"               → ("NADPH",            None, False)
    """
    is_unsat = species_name.endswith("_un")
    core = species_name[:-3] if is_unsat else species_name
    m = _CHAIN_PREFIX.match(core)
    if m is None:
        return core, None, is_unsat
    return m.group(2), int(m.group(1)), is_unsat


def _collect_species_stats(
    reactions: list[_Reaction],
) -> tuple[dict[str, set[str]], set[str], set[str]]:
    """Return (species_to_rxns, forward_products, all_reactants)."""
    species_to_rxns: dict[str, set[str]] = defaultdict(set)
    forward_products: set[str] = set()
    all_reactants: set[str] = set()

    for rxn in reactions:
        for sp in rxn.reactants:
            species_to_rxns[sp].add(rxn.rxn_name)
            all_reactants.add(sp)
        for sp in rxn.products:
            species_to_rxns[sp].add(rxn.rxn_name)
            forward_products.add(sp)

    return dict(species_to_rxns), forward_products, all_reactants


# ═══════════════════════════════════════════════════════════════════════════
# Check 1 — Reaction balance
# ═══════════════════════════════════════════════════════════════════════════

def check_balances(
    reactions: list[_Reaction],
    moieties: list[str] | None = None,
    tol: float = DEFAULT_TOLERANCE,
) -> BalanceResult:
    """Check that each expanded reaction is balanced for carbon and the given moieties.

    NAD  tracks both NAD and NADH as a combined pool (so NADH → NAD is balanced).
    NADP tracks both NADP and NADPH as a combined pool.
    CoA  matches any token ending in "CoA" (MalCoA, AcCoA, CoA itself, ...).
    ACP  matches any token ending in "ACP" (MalACP, BKeAcACP, ACP itself, ...).
    """
    if moieties is None:
        moieties = DEFAULT_MOIETIES
    tracked = ["carbon"] + moieties
    imbalanced: list[tuple[str, str, dict[str, float]]] = []
    balanced_count = 0

    for rxn in reactions:
        deltas = _compute_deltas(rxn, moieties)
        failures = {k: deltas.get(k, 0.0) for k in tracked if abs(deltas.get(k, 0.0)) > tol}
        if failures:
            imbalanced.append((rxn.rxn_name, rxn.reaction_expression(), failures))
        else:
            balanced_count += 1

    return BalanceResult(imbalanced=imbalanced, balanced_count=balanced_count, moieties=moieties)


def print_balance_report(result: BalanceResult) -> None:
    """Print a concise balance check report."""
    total = result.balanced_count + len(result.imbalanced)
    _section("MASS BALANCE")
    print(f"  Moieties: Carbon, {', '.join(result.moieties)}")
    print(f"  {result.balanced_count}/{total} reactions balanced")
    if not result.imbalanced:
        print("  All reactions balanced ✓")
        return
    print()
    records = []
    for rxn_name, expr, failures in result.imbalanced:
        row: dict = {"rxn_name": rxn_name, "expression": expr}
        row.update({f"Δ{k}": f"{v:+g}" for k, v in sorted(failures.items())})
        records.append(row)
    _display_df(records)


# ═══════════════════════════════════════════════════════════════════════════
# Check 2 — Species continuity
# ═══════════════════════════════════════════════════════════════════════════

def check_species_continuity(reactions: list[_Reaction]) -> ContinuityResult:
    """Audit species flow through the network.

    never_created_fwd  — never appear as a forward-direction product
                         (initial inputs or possible typos)
    never_consumed     — never appear as a reactant
                         (terminal outputs or possible typos)
    single_rxn_species — appear in exactly one reaction
                         (possible dead-ends or name mistypes)
    """
    species_to_rxns, forward_products, all_reactants = _collect_species_stats(reactions)
    all_species = set(species_to_rxns.keys())

    never_created_fwd = sorted(all_species - forward_products)
    never_consumed     = sorted(all_species - all_reactants)

    single_rxn: list[tuple[str, str]] = sorted(
        [
            (sp, next(iter(rxns_set)))
            for sp, rxns_set in species_to_rxns.items()
            if len(rxns_set) == 1
        ],
        key=lambda x: x[0],
    )

    return ContinuityResult(
        never_created_fwd=never_created_fwd,
        never_consumed=never_consumed,
        single_rxn_species=single_rxn,
        species_to_rxns=species_to_rxns,
    )


def print_continuity_report(result: ContinuityResult) -> None:
    """Print the species continuity report."""
    _section("SPECIES CONTINUITY CHECK")
    print(f"  Total species:                      {len(result.species_to_rxns)}")
    print(f"  Never created as a forward product: {len(result.never_created_fwd)}")
    print(f"  Never consumed as a reactant:       {len(result.never_consumed)}")
    print(f"  Appear in exactly one reaction:     {len(result.single_rxn_species)}")

    if result.never_created_fwd:
        print()
        print("  [INFO] Never created in forward reactions (starting substrates check):")
        _display_df([
            {"species": sp,
             "used_in": ", ".join(sorted(result.species_to_rxns.get(sp, set())))}
            for sp in result.never_created_fwd
        ])

    if result.never_consumed:
        print()
        print("  [INFO] Never consumed in forward reactions (terminal products or sinks check):")
        _display_df([
            {"species": sp,
             "produced_in": ", ".join(sorted(result.species_to_rxns.get(sp, set())))}
            for sp in result.never_consumed
        ])

    if result.single_rxn_species:
        print()
        print("  [WARN] Species appearing in exactly one reaction (possible dead-end or mistype):")
        _display_df([{"species": sp, "reaction": rxn} for sp, rxn in result.single_rxn_species])


# ═══════════════════════════════════════════════════════════════════════════
# Check 3 — Chain-set consistency
# ═══════════════════════════════════════════════════════════════════════════

def check_chain_sets(
    reactions: list[_Reaction],
) -> dict[tuple[str, bool], ChainFamilyResult]:
    """For every species family at ≥2 distinct chain lengths, compare which chains
    are produced (appear in forward products) vs. consumed (appear as reactants).

    Returns a dict keyed by (family_name, is_unsat).
    """
    producer_chains: dict[tuple[str, bool], set[int]] = defaultdict(set)
    consumer_chains: dict[tuple[str, bool], set[int]] = defaultdict(set)

    for rxn in reactions:
        for sp in rxn.products:
            family, chain, is_unsat = _extract_family(sp)
            if chain is not None:
                producer_chains[(family, is_unsat)].add(chain)
        for sp in rxn.reactants:
            family, chain, is_unsat = _extract_family(sp)
            if chain is not None:
                consumer_chains[(family, is_unsat)].add(chain)

    all_keys = set(producer_chains) | set(consumer_chains)
    results: dict[tuple[str, bool], ChainFamilyResult] = {}

    for key in sorted(all_keys, key=lambda k: (k[0], k[1])):
        family, is_unsat = key
        prod = producer_chains.get(key, set())
        cons = consumer_chains.get(key, set())
        if len(prod | cons) < 2:
            continue   # single-chain family — not a useful comparison
        results[key] = ChainFamilyResult(
            family=family,
            is_unsat=is_unsat,
            producer_chains=prod,
            consumer_chains=cons,
        )

    return results


def print_chain_set_report(
    results: dict[tuple[str, bool], ChainFamilyResult],
) -> None:
    """Print the chain-set consistency report."""
    _section("CHAIN-SET CONSISTENCY CHECK")

    pure_sinks:   list[ChainFamilyResult] = []
    pure_sources: list[ChainFamilyResult] = []
    warnings:     list[ChainFamilyResult] = []
    clean:        list[ChainFamilyResult] = []

    for r in results.values():
        if r.is_pure_sink:
            pure_sinks.append(r)
        elif r.is_pure_source:
            pure_sources.append(r)
        elif r.orphaned_products or r.orphaned_reactants:
            warnings.append(r)
        else:
            clean.append(r)

    print(f"  Families with multiple chain lengths:    {len(results)}")
    print(f"  Fully matched (produced = consumed):     {len(clean)}")
    print(f"  Pure-sink families (never consumed):     {len(pure_sinks)}")
    print(f"  Pure-source families (never produced):   {len(pure_sources)}")
    print(f"  Partially matched (chain-set mismatch):  {len(warnings)}")

    if pure_sources:
        print()
        print("  [ERROR] Families consumed at some chains but never produced at any chain in forward reactions:")
        _display_df([
            {"family": r.family + (" (unsat)" if r.is_unsat else ""),
             "consumed_chains": str(sorted(r.consumer_chains))}
            for r in sorted(pure_sources, key=lambda x: (x.family, x.is_unsat))
        ])

    if warnings:
        print()
        print("  [WARN] Chain-set mismatches:")
        records: list[dict] = []
        for r in sorted(warnings, key=lambda x: (x.family, x.is_unsat)):
            sfx = " (unsat)" if r.is_unsat else ""
            if r.orphaned_reactants:
                records.append({
                    "family": r.family + sfx, "issue": "MISSING PRODUCER",
                    "chains": str(sorted(r.orphaned_reactants)),
                })
            if r.orphaned_products:
                records.append({
                    "family": r.family + sfx, "issue": "MISSING CONSUMER",
                    "chains": str(sorted(r.orphaned_products)),
                })
        _display_df(records)

    if pure_sinks:
        print()
        print("  [INFO] Pure-sink families (expected terminal products):")
        _display_df([
            {"family": r.family + (" (unsat)" if r.is_unsat else ""),
             "chains": str(sorted(r.producer_chains))}
            for r in sorted(pure_sinks, key=lambda x: (x.family, x.is_unsat))
        ])


# ═══════════════════════════════════════════════════════════════════════════
# Check 4 — Name similarity
# ═══════════════════════════════════════════════════════════════════════════

def _similarity_pairs(
    names: list[str],
    threshold: float,
    kind: str,
    skip_substrings: bool = True,
) -> list[SimilarityWarning]:
    """Return SimilarityWarning entries for all pairs in *names* above *threshold*."""
    warnings: list[SimilarityWarning] = []
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            if skip_substrings and (a in b or b in a):
                continue
            score = SequenceMatcher(None, a, b).ratio()
            if score >= threshold:
                if a.lower() == b.lower():
                    note = "capitalization mismatch"
                else:
                    note = f"high similarity ({score:.2f})"
                warnings.append(SimilarityWarning(family_a=a, family_b=b, score=score, note=note, kind=kind))
    return warnings


def check_name_similarity(
    reactions: list[_Reaction],
    threshold: float = DEFAULT_SIMILARITY_THRESHOLD,
) -> list[SimilarityWarning]:
    """Flag suspiciously similar species family names and parameter names.

    Species families are derived by stripping the C{N}_ chain prefix and _un
    suffix.  Pairs where one name is a substring of the other are skipped for
    species (naturally related names like FabB_Act / FabB_Act_MalACP) but not
    for parameters (short keys like k1f / k1r must still be compared).
    """
    all_species: set[str] = set()
    for rxn in reactions:
        all_species.update(rxn.reactants)
        all_species.update(rxn.products)

    families: set[str] = set()
    for sp in all_species:
        family, _, _ = _extract_family(sp)
        families.add(family)

    param_keys: set[str] = set()
    for rxn in reactions:
        fwd = getattr(rxn, "rate_const_key", None)
        rvs = getattr(rxn, "rvs_rate_const_key", None)
        if fwd:
            param_keys.add(fwd)
        if rvs:
            param_keys.add(rvs)

    warnings: list[SimilarityWarning] = (
        _similarity_pairs(sorted(families),   threshold, kind="species",   skip_substrings=True)
        + _similarity_pairs(sorted(param_keys), threshold, kind="parameter", skip_substrings=False)
    )
    return sorted(warnings, key=lambda w: (-w.score, w.kind))


def print_similarity_report(warnings: list[SimilarityWarning]) -> None:
    """Print the name-similarity report."""
    _section("NAME SIMILARITY CHECK")
    if not warnings:
        print("  No suspicious name pairs found ✓")
        return
    sp_warnings  = [w for w in warnings if w.kind == "species"]
    pm_warnings  = [w for w in warnings if w.kind == "parameter"]
    print(f"  {len(warnings)} suspicious pair(s): {len(sp_warnings)} species, {len(pm_warnings)} parameter")
    if sp_warnings:
        print()
        print("  Species families:")
        _display_df([
            {"name_a": w.family_a, "name_b": w.family_b, "score": f"{w.score:.2f}", "note": w.note}
            for w in sp_warnings
        ])
    if pm_warnings:
        print()
        print("  Parameter keys:")
        _display_df([
            {"name_a": w.family_a, "name_b": w.family_b, "score": f"{w.score:.2f}", "note": w.note}
            for w in pm_warnings
        ])


# ═══════════════════════════════════════════════════════════════════════════
# Check 5 — Zero-rate reactions
# ═══════════════════════════════════════════════════════════════════════════

def check_zero_rates(reactions: list[_Reaction]) -> list[ZeroRateResult]:
    """Flag any reactions with a zero forward or reverse rate constant."""
    results: list[ZeroRateResult] = []
    for rxn in reactions:
        fwd_zero = rxn.rate_const_value == 0.0
        rvs_zero = rxn.reversible and rxn.rvs_rate_const_value == 0.0
        if fwd_zero and rvs_zero:
            direction = "both"
        elif fwd_zero:
            direction = "forward"
        elif rvs_zero:
            direction = "reverse"
        else:
            continue
        results.append(
            ZeroRateResult(
                rxn_name=rxn.rxn_name,
                expression=rxn.reaction_expression(),
                direction=direction,
            )
        )
    return results


def print_zero_rate_report(results: list[ZeroRateResult]) -> None:
    """Print the zero-rate reactions report."""
    _section("ZERO-RATE REACTIONS")
    if not results:
        print("  No zero-rate reactions ✓")
        return
    print(f"  {len(results)} reaction(s) with at least one zero rate constant:")
    _display_df([
        {"rxn_name": r.rxn_name, "direction": r.direction, "expression": r.expression}
        for r in results
    ])


# ═══════════════════════════════════════════════════════════════════════════
# Check 6 — Irreversible accumulation / drain
# ═══════════════════════════════════════════════════════════════════════════

def check_irreversible_flow(reactions: list[_Reaction]) -> IrreversibleFlowResult:
    """Flag species with a one-way irreversible flow imbalance.

    A species is *fully generated* across the network if it appears as
    a forward product of any reaction, OR as a reactant in any reversible
    reaction (the reverse direction generates it).  Likewise it is *fully
    consumed* if it appears as a forward reactant of any reaction OR as a
    product in any reversible reaction (the reverse direction consumes it).

    Two situations are flagged:
    - **Irreversibly generated, never consumed** — produced by ≥1 irreversible
      forward reaction AND not consumed anywhere (neither as a fwd reactant
      nor via any reverse direction).  Will accumulate without bound.
    - **Irreversibly consumed, never generated** — consumed by ≥1 irreversible
      forward reaction AND not generated anywhere (neither as a fwd product
      nor via any reverse direction).  Will drain to zero.
    """
    # Full generation set: fwd products + reactants of reversible rxns
    full_generated: set[str] = set()
    # Full consumption set: fwd reactants + products of reversible rxns
    full_consumed: set[str] = set()
    # Irreversible-only maps: species → list of responsible rxn_names
    irrev_gen_rxns: dict[str, list[str]] = defaultdict(list)
    irrev_con_rxns: dict[str, list[str]] = defaultdict(list)

    for rxn in reactions:
        for sp in rxn.products:
            full_generated.add(sp)
            if not rxn.reversible:
                irrev_gen_rxns[sp].append(rxn.rxn_name)
        for sp in rxn.reactants:
            full_consumed.add(sp)
            if not rxn.reversible:
                irrev_con_rxns[sp].append(rxn.rxn_name)
        if rxn.reversible:
            # Reverse direction: reactants are generated, products are consumed
            for sp in rxn.reactants:
                full_generated.add(sp)
            for sp in rxn.products:
                full_consumed.add(sp)

    irrev_gen_never_consumed = sorted(
        [(sp, rxns) for sp, rxns in irrev_gen_rxns.items() if sp not in full_consumed],
        key=lambda x: x[0],
    )
    irrev_consumed_never_gen = sorted(
        [(sp, rxns) for sp, rxns in irrev_con_rxns.items() if sp not in full_generated],
        key=lambda x: x[0],
    )

    return IrreversibleFlowResult(
        irrev_gen_never_consumed=irrev_gen_never_consumed,
        irrev_consumed_never_gen=irrev_consumed_never_gen,
    )


def print_irreversible_flow_report(result: IrreversibleFlowResult) -> None:
    """Print the irreversible accumulation / drain report."""
    _section("IRREVERSIBLE ACCUMULATION AND DRAIN CHECK")
    acc = result.irrev_gen_never_consumed
    drn = result.irrev_consumed_never_gen
    print(f"  Irreversibly generated, never consumed: {len(acc)}")
    print(f"  Irreversibly consumed, never generated: {len(drn)}")
    if not acc and not drn:
        print("  No irreversible accumulation or drain issues ✓")
        return
    if acc:
        print()
        print("  [ACCUMULATE] Generated by irreversible reaction(s) but never consumed:")
        _display_df([
            {"species": sp, "source_reactions": ", ".join(rxn_names)}
            for sp, rxn_names in acc
        ])
    if drn:
        print()
        print("  [DRAIN] Consumed by irreversible reaction(s) but never generated:")
        _display_df([
            {"species": sp, "consuming_reactions": ", ".join(rxn_names)}
            for sp, rxn_names in drn
        ])


# ═══════════════════════════════════════════════════════════════════════════
# Check 7 — Parameter conflicts
# ═══════════════════════════════════════════════════════════════════════════

def check_parameter_conflicts(reactions: list[_Reaction]) -> list[ParamConflictResult]:
    """Detect parameter names that are assigned different values across reactions.

    Checks both forward (rate_const_key / rate_const_value) and reverse
    (rvs_rate_const_key / rvs_rate_const_value) rate constants.
    A conflict is flagged when the same key appears with two or more distinct
    numeric values in any combination of reactions or directions.
    """
    param_assignments: dict[str, list[tuple[str, str, float]]] = defaultdict(list)

    for rxn in reactions:
        fwd_key = getattr(rxn, "rate_const_key", None)
        if fwd_key is not None and rxn.rate_const_value is not None:
            param_assignments[fwd_key].append((rxn.rxn_name, "fwd", float(rxn.rate_const_value)))
        rvs_key = getattr(rxn, "rvs_rate_const_key", None)
        if rvs_key is not None and rxn.rvs_rate_const_value is not None:
            param_assignments[rvs_key].append((rxn.rxn_name, "rvs", float(rxn.rvs_rate_const_value)))

    results: list[ParamConflictResult] = []
    for param_name, assignments in sorted(param_assignments.items()):
        distinct_values = {val for _, _, val in assignments}
        if len(distinct_values) > 1:
            results.append(ParamConflictResult(param_name=param_name, assignments=assignments))

    return results


def print_parameter_conflict_report(results: list[ParamConflictResult]) -> None:
    """Print the parameter conflict report."""
    _section("PARAMETER CONFLICT CHECK")
    if not results:
        print("  No parameter conflicts ✓")
        return
    print(f"  {len(results)} parameter(s) assigned different values across reactions:")
    rows = []
    for r in results:
        distinct_values = sorted({val for _, _, val in r.assignments})
        for rxn_name, direction, val in r.assignments:
            rows.append({
                "param_name": r.param_name,
                "distinct_values": str(distinct_values),
                "rxn_name": rxn_name,
                "direction": direction,
                "value": val,
            })
    _display_df(rows)


# ═══════════════════════════════════════════════════════════════════════════
# Master entry point
# ═══════════════════════════════════════════════════════════════════════════

def run_all_checks(
    reactions: list[Any],
    moieties: list[str] | None = None,
    tol: float = DEFAULT_TOLERANCE,
    similarity_threshold: float = DEFAULT_SIMILARITY_THRESHOLD,
) -> dict[str, Any]:
    """Run all sanity checks on a pre-loaded reaction list. Includs carbon mass balance, 
    moiety balance, species continuity, reaction family chain consistency, name similarity, zero-rate 
    reactions, irreversible flow imbalances, and parameter value conflicts.

    Parameters
    ----------
    reactions            : list of ElementaryReaction objects from reaction_model_builder
    moieties             : moieties to balance-check in addition to carbon (default: CoA, ACP, NAD, NADP)
    tol                  : balance tolerance           (default: 1e-9)
    similarity_threshold : minimum SequenceMatcher ratio for name-similarity warnings
                           (default: 0.90)

    Returns
    -------
    dict with keys: reactions, balance, continuity, chain_sets, similarity,
                    zero_rates, irrev_flow, param_conflicts
    """
    if moieties is None:
        moieties = DEFAULT_MOIETIES

    print(f"Running sanity checks on {len(reactions)} expanded reactions\n")

    balance         = check_balances(reactions, moieties=moieties, tol=tol)
    continuity      = check_species_continuity(reactions)
    chain_sets      = check_chain_sets(reactions)
    similarity      = check_name_similarity(reactions, threshold=similarity_threshold)
    zero_rates      = check_zero_rates(reactions)
    irrev_flow      = check_irreversible_flow(reactions)
    param_conflicts = check_parameter_conflicts(reactions)

    print_balance_report(balance)
    print()
    print_continuity_report(continuity)
    print()
    print_chain_set_report(chain_sets)
    print()
    print_similarity_report(similarity)
    print()
    print_zero_rate_report(zero_rates)
    print()
    print_irreversible_flow_report(irrev_flow)
    print()
    print_parameter_conflict_report(param_conflicts)

    return {
        "reactions":       reactions,
        "balance":         balance,
        "continuity":      continuity,
        "chain_sets":      chain_sets,
        "similarity":      similarity,
        "zero_rates":      zero_rates,
        "irrev_flow":      irrev_flow,
        "param_conflicts": param_conflicts,
    }
