"""Reaction-set variant for the grouping test: TesA's `c3` split into two groups.

`c3` multiplies TesA's hydrolysis kcat at every chain length -- six constants with six
distinct nominal values, all assumed to move together. The grouping test asks whether the
data support one multiplier or need two, so this writes a copy of a reaction set in which the
hydrolysis entry is split in two:

  c3s   short chains, C4-C8
  c3l   long chains, C10 and up, including the unsaturated species

Every other file is copied byte for byte, and the rate constants are untouched, so the
variant with c3s = c3l = 1 is the same model as the original with c3 = 1. `--check` confirms
that by solving both at the Tier-1 baseline and comparing every fatty-acid species.

Written by script rather than by hand because chain lists and their value lists must stay
positionally aligned (see Utilities/generate_chain_systems.py).

Usage: python make_c3_split_variant.py [--system C14+unsat] [--split_below 10] [--check]
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

import yaml

HERE = Path(__file__).resolve().parent
PROJECT = HERE.parent.parent
RX_ROOT = PROJECT / "Reactions" / "EC_FAS_ME1"


def split_entry(entry, split_below):
    """Two copies of the c3 hydrolysis entry, partitioned by chain length."""
    sat = entry["sat_chain_lengths"]
    vals = entry["rate_const_value"]
    if len(sat) != len(vals):
        raise SystemExit(f"{entry['rxn_name']}: {len(sat)} chains but {len(vals)} values")
    unsat = entry.get("unsat_chain_lengths") or []
    out = []
    for group, keep in (("c3s", lambda n: n < split_below), ("c3l", lambda n: n >= split_below)):
        idx = [i for i, n in enumerate(sat) if keep(n)]
        e = dict(entry)
        e["sat_chain_lengths"] = [sat[i] for i in idx]
        e["rate_const_value"] = [vals[i] for i in idx]
        u = [n for n in unsat if keep(n)]
        if u:
            e["unsat_chain_lengths"] = u
        else:
            e.pop("unsat_chain_lengths", None)
        e["scaling_group"] = group
        out.append(e)
    return out


def write_variant(system, split_below):
    src, dst = RX_ROOT / system, RX_ROOT / f"{system}+c3split"
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    tesa = yaml.safe_load((src / "TesA.yaml").read_text())
    hits = [i for i, r in enumerate(tesa["reactions"]) if r.get("scaling_group") == "c3"]
    if len(hits) != 1:
        raise SystemExit(f"expected exactly one c3 entry in {system}/TesA.yaml, found {len(hits)}")
    i = hits[0]
    tesa["reactions"][i:i + 1] = split_entry(tesa["reactions"][i], split_below)
    header = "".join(l for l in (src / "TesA.yaml").read_text().splitlines(True) if l.startswith("#"))
    note = (f"# GENERATED by job_files/tier1/make_c3_split_variant.py from {system}/TesA.yaml:\n"
            f"# c3 split into c3s (chains < {split_below}) and c3l (chains >= {split_below}).\n")
    (dst / "TesA.yaml").write_text(header + note + yaml.safe_dump(tesa, sort_keys=False, width=200))
    return dst


def check(system):
    """Same model at c3s = c3l = 1: baseline fatty acids must match the original."""
    sys.path.insert(0, str(PROJECT / "Utilities"))
    import numpy as np
    import generate_chain_data as gcd

    def baseline(rx):
        groups = gcd.discover_scaling_groups(rx)
        s = gcd.ChainSystem(rx, 1e-8, 1e-10,
                            scaling_group_overrides=gcd.nominal_scaling_group_overrides(sorted(groups)))
        fa = sorted(x for x in s.species if re.fullmatch(r"C\d+_FA(_unsat)?", x))
        _, ys = s.solve(s.y0(), max_steps=200_000, save_steps=False)
        if ys is None:
            raise SystemExit(f"baseline solve failed for {rx.name}")
        return fa, np.asarray(ys)[-1, [s.index_of[x] for x in fa]], sorted(groups)

    fa0, y0, g0 = baseline(RX_ROOT / system)
    fa1, y1, g1 = baseline(RX_ROOT / f"{system}+c3split")
    assert fa0 == fa1, "species differ"
    rel = float(np.max(np.abs(y1 - y0) / np.maximum(np.abs(y0), 1e-30)))
    print(f"groups: original {g0}\n        variant  {g1}")
    print(f"max relative difference over {len(fa0)} FA species at 720 s: {rel:.2e}")
    if rel > 1e-8:
        raise SystemExit("variant does not reproduce the original model")


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--system", default="C14+unsat")
    ap.add_argument("--split_below", type=int, default=10)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    dst = write_variant(a.system, a.split_below)
    print(f"wrote {dst.relative_to(PROJECT)}")
    if a.check:
        check(a.system)


if __name__ == "__main__":
    main()
